Addition of HV issues algorithm
pillot/AliceO2 pull request #5
Opened 2024-06-24 12:00 UTC by comrademarvin

Added the algorithm to find HV issues as the findBadHVs function in the HVStatusCreator, as well as the required parameters in the StatusMapCreatorParam.

2024-06-24 16:38 UTC, pillot requested changes
Hi Stephan, thanks for the PR.

There are some trailing spaces at the end of a few lines that the code formatter does not like. It would be nice if you could remove them while addressing my other comments.

You can simply push a new commit with your modifications into your branch (or push --force if you modify your previous commits) to automatically update this PR.

Cheers,
Philippe

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> +  using DPMAP2 = std::map<std::string, std::map<uint64_t, double>>;
this can be moved to private, or to the .cxx if decodeDPMAP(...) becomes a function in the .cxx

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> +      if ((end - begin) < StatusMapCreatorParam::Instance().minDuration) return false;
This test can be done while producing the list of HV issues, to prevent the addition of a new issue if it is too short.

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> +#include "MCHStatus/StatusMapCreatorParam.h"
once you move the test on the duration of HV issues, this include can be move to the .cxx

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +float sum(float s, o2::dcs::DataPointValue v);
you can implement the function here rather that just declaring it

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> +  DPMAP2 decodeDPMAP(const DPMAP& dpMap);
this could also be a function in the .cxx, but I don't have strong opinion on that.

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +  for (auto& entry : dpMap) {
shouldn't it be `const`?
you could also use `const auto& [dpId, dpsHV]`

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +      auto dpsHV = entry.second;
here you copy all data points

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +      dps2.emplace(9999999999999, sum(0.0, lastPoint));
it might be better to use `std::numeric_limits<uint64_t>::max()`, but one has to be careful when adding some margin to compare TF time with HV issue time range. Same is true with the first point at 0.

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +float sum(float s, o2::dcs::DataPointValue v)
Why a sum and not the converter used in the macro, which directly returns the value as double?

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +
the internal map of issues must be cleared before being filled with new issues.

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +      if (valueHV < StatusMapCreatorParam::Instance().hvLimits[chamber]) { // check whether HV point is below set threshold for chamber
It would probably be more efficient to get the HV limit for this chamber once outside of the loop over data points

2024-06-24 16:38 UTC, pillot commented on Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> +      this->mBadHVTimeRanges.emplace(alias, hvIssuesList);
`this->` can be omitted

2024-06-25 10:18 UTC, comrademarvin commented
Hi Philippe,

Thank you for the feedback. I am making the changes now. Will also re-run
my tests before updating the pull-request.

I am not too sure what you mean by "one has to be careful when adding some
margin to compare TF time with HV issue time range". I naively thought that
the timestamps are just integers, so if you make it zero or very large you
can still compare as numbers and a timestamp will always be greater than 0
and less than the maximum number. What am I missing?

Cheers,
Stephan

On Mon, Jun 24, 2024 at 6:38 PM pillot ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi Stephan, thanks for the PR.
>
> There are some trailing spaces at the end of a few lines that the code
> formatter does not like. It would be nice if you could remove them while
> addressing my other comments.
>
> You can simply push a new commit with your modifications into your branch
> (or push --force if you modify your previous commits) to automatically
> update this PR.
>
> Cheers,
> Philippe
> ------------------------------
>
> In Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651206177>:
>
> > @@ -50,6 +51,7 @@ class HVStatusCreator
>    using DPID = dcs::DataPointIdentifier;
>    using DPVAL = dcs::DataPointValue;
>    using DPMAP = std::unordered_map<DPID, std::vector<DPVAL>>;
> +  using DPMAP2 = std::map<std::string, std::map<uint64_t, double>>;
>
> this can be moved to private, or to the .cxx if decodeDPMAP(...) becomes a
> function in the .cxx
> ------------------------------
>
> In Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651211225>:
>
> >       */
> -    bool contains(uint64_t timestamp) const { return timestamp >= begin && timestamp < end; }
> +    bool contains(uint64_t timestamp) const {
> +      if ((end - begin) < StatusMapCreatorParam::Instance().minDuration) return false;
>
> This test can be done while producing the list of HV issues, to prevent
> the addition of a new issue if it is too short.
> ------------------------------
>
> In Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651212781>:
>
> > @@ -19,6 +19,7 @@
>
>  #include "DetectorsDCS/DataPointIdentifier.h"
>  #include "DetectorsDCS/DataPointValue.h"
> +#include "MCHStatus/StatusMapCreatorParam.h"
>
> once you move the test on the duration of HV issues, this include can be
> move to the .cxx
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651215704>:
>
> > @@ -17,12 +17,53 @@
>  #include "MCHGlobalMapping/Mapper.h"
>  #include "MCHStatus/StatusMap.h"
>
> +float sum(float s, o2::dcs::DataPointValue v);
>
> you can implement the function here rather that just declaring it
> ------------------------------
>
> In Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651221288>:
>
> >    };
>
>    /// map of bad HV channels with the time ranges concerned
>    std::unordered_map<std::string, std::vector<TimeRange>> mBadHVTimeRanges{};
>    std::set<std::string> mCurrentBadHVs{}; ///< current list of bad HV channels
> +
> +  /**
> +   * @brief decode the DCS DPMAP to be processed for HV issues
> +   * @param dpMap encoded DCS HV data points from CCDB
> +   * @return the decoded DPMAP2
> +   */
> +  DPMAP2 decodeDPMAP(const DPMAP& dpMap);
>
> this could also be a function in the .cxx, but I don't have strong opinion
> on that.
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651240060>:
>
> > @@ -60,4 +101,43 @@ void HVStatusCreator::updateStatusMap(StatusMap& statusMap)
>    }
>  }
>
> +HVStatusCreator::DPMAP2 HVStatusCreator::decodeDPMAP(const DPMAP& dpMap) {
> +  DPMAP2 dpsMapPerAlias;
> +
> +  for (auto& entry : dpMap) {
>
> shouldn't it be const?
> you could also use const auto& [dpId, dpsHV]
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651242447>:
>
> > @@ -60,4 +101,43 @@ void HVStatusCreator::updateStatusMap(StatusMap& statusMap)
>    }
>  }
>
> +HVStatusCreator::DPMAP2 HVStatusCreator::decodeDPMAP(const DPMAP& dpMap) {
> +  DPMAP2 dpsMapPerAlias;
> +
> +  for (auto& entry : dpMap) {
> +    std::string alias = (entry.first).get_alias();
> +
> +    if (alias.find("vMon") != std::string::npos) { // only consider voltage channels
> +      auto dpsHV = entry.second;
>
> here you copy all data points
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651257344>:
>
> > +    if (alias.find("vMon") != std::string::npos) { // only consider voltage channels
> +      auto dpsHV = entry.second;
> +      auto& dps2 = dpsMapPerAlias[alias];
> +
> +      // copy first point to the beginning of time
> +      auto firstPoint = dpsHV.front();
> +      dps2.emplace(0, sum(0.0, firstPoint));
> +
> +      for (const auto& value : dpsHV) {
> +        double valueConverted = sum(0.0, value);
> +        dps2.emplace(value.get_epoch_time(), valueConverted);
> +      }
> +
> +      // copy last point to the end of time
> +      auto lastPoint = dpsHV.back();
> +      dps2.emplace(9999999999999, sum(0.0, lastPoint));
>
> it might be better to use std::numeric_limits<uint64_t>::max(), but one
> has to be careful when adding some margin to compare TF time with HV issue
> time range. Same is true with the first point at 0.
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651271934>:
>
> >  } // namespace o2::mch
> +
> +// converts DCS data point value to double HV value
> +float sum(float s, o2::dcs::DataPointValue v)
>
> Why a sum and not the converter used in the macro, which directly returns
> the value as double?
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651304286>:
>
> >  namespace o2::mch
>  {
>
>  void HVStatusCreator::findBadHVs(const DPMAP& dpMap)
>  {
> +  // decode the DCS DPMAP
> +  DPMAP2 dpsMapPerAlias = decodeDPMAP(dpMap);
> +
>
> the internal map of issues must be cleared before being filled with new
> issues.
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651307543>:
>
> >  namespace o2::mch
>  {
>
>  void HVStatusCreator::findBadHVs(const DPMAP& dpMap)
>  {
> +  // decode the DCS DPMAP
> +  DPMAP2 dpsMapPerAlias = decodeDPMAP(dpMap);
> +
> +  // Find list of HV issues per alias
> +  for (const auto& [alias, dpsHV] : dpsMapPerAlias) {
> +    int chamber = o2::mch::dcs::toInt(o2::mch::dcs::aliasToChamber(alias));
> +    std::vector<TimeRange> hvIssuesList;
> +
> +    uint64_t tStart, tStop = 0;
> +    bool ongoingIssue = false;
> +
> +    for (auto& [timestamp, valueHV] : dpsHV) {
> +      if (valueHV < StatusMapCreatorParam::Instance().hvLimits[chamber]) { // check whether HV point is below set threshold for chamber
>
> It would probably be more efficient to get the HV limit for this chamber
> once outside of the loop over data points
> ------------------------------
>
> In Detectors/MUON/MCH/Status/src/HVStatusCreator.cxx
> <https://github.com/pillot/AliceO2/pull/5#discussion_r1651310469>:
>
> >
> +    // add issues for the alias if non-empty
> +    if (!hvIssuesList.empty()) {
> +      this->mBadHVTimeRanges.emplace(alias, hvIssuesList);
>
> this-> can be omitted
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pillot/AliceO2/pull/5#pullrequestreview-2136092395>,
> or un [...]

2024-06-25 10:43 UTC, pillot commented
> I am not too sure what you mean by "one has to be careful when adding some margin to compare TF time with HV issue time range". I naively thought that the timestamps are just integers, so if you make it zero or very large you can still compare as numbers and a timestamp will always be greater than 0 and less than the maximum number. What am I missing?

There is no problem in principle, just that if we add some margin we must pay attention not to add (or subtract) value to the time range (e.g. t < t_min - 1) to avoid range_error issues.

2024-06-26 09:45 UTC, comrademarvin commented
Hi Philippe!

I have made your requested changed and tested again to make sure it still reproduces the correct issues.

For now I have left the extension of the boundaries to zero and the max. Do you think there isa better way to do this to avoid potential range errors? For example, to add a fixed finite margin of time?

Let me know if there are any additional changes to be made.

Cheers,
Stephan

2024-06-26 10:07 UTC, pillot requested changes

2024-06-26 10:07 UTC, pillot commented on Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> +  using DPMAP2 = std::map<std::string, std::map<uint64_t, double>>;
you can remove this as it has been moved to the .cxx

2024-06-26 10:07 UTC, pillot commented on Detectors/MUON/MCH/Status/include/MCHStatus/HVStatusCreator.h
> +  DPMAP2 decodeDPMAP(const DPMAP& dpMap);
you can remove this as it has been moved to the .cxx

2024-06-26 10:14 UTC, pillot commented
Hi Stefan, thanks for the changes.

There are just 2 leftovers from the previous version. Once removed, I will merge and address the formatting issues, then I will rebase the branch.

> For now I have left the extension of the boundaries to zero and the max. Do you think there isa better way to do this to avoid potential range errors? For example, to add a fixed finite margin of time?

No it's fine, I will just keep that in mind when using the range for comparison.

Cheers,
Philippe

2024-06-26 11:09 UTC, comrademarvin commented
> There are just 2 leftovers from the previous version. Once removed, I will merge and address the formatting issues, then I will rebase the branch.
> 

Thought I had removed it, sorry about that. Have removed it now.

I see that the clang format test fails. What is the formatting it requires?

2024-06-26 12:03 UTC, pillot commented
There is a .clang-format in the O2 top repository. My editor (VS-code) is configured to use it. There are also some (old) guidelines here: https://github.com/AliceO2Group/CodingGuidelines. Alternatively you can open the details of the failing check and address the defaults manually.

> Le 26 juin 2024 à 13:09, Stephan Potgieter ***@***.***> a écrit :
> 
> 
> There are just 2 leftovers from the previous version. Once removed, I will merge and address the formatting issues, then I will rebase the branch.
> 
> Thought I had removed it, sorry about that. Have removed it now.
> 
> I see that the clang format test fails. What is the formatting it requires?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/pillot/AliceO2/pull/5#issuecomment-2191429711>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AD3AGBKTJVNBY7P5M6P3CNTZJKOOPAVCNFSM6AAAAABJZVTDAOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJRGQZDSNZRGE>.
> You are receiving this because you commented.
>

2024-06-27 12:25 UTC, pillot approved these changes

2024-06-27 12:29 UTC, merged